feat(network): add the client (#146)
* feat(Client): add base network with connection

* feat(client): add the component and the outbox handler

* feat(client): add the networkcontrol which pack the control infos

* refactor(client): change the network client to a singleton

* feat(client): add the system that sends ack to server

* feat(networkcontrol): make it so it doesn't send useless movements

* feat(client): add inbox buffering and isconnected boolean

* docs(client): add missing doxygen to some client systems

* refactor: remove useless include in main

* fix(NetworkControl): make it so that when no inputs are made no request is made

* fix(MessageQueue): remove the pqueue clear to create one

* feat(Client): add deconnection method and move some var

* refactor: fix coding style issues

* ci: add logs for coding style

* build: change log filename

* chore: add logfile in gitignore

* refactor(core): coding style

---------

Co-authored-by: queng <quentin.brejoin@gmail.com>

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -61,6 +61,11 @@ jobs:
       - name: Check coding style
         run: |
           ./coding-style.sh
+          if [ $? -ne 0 ]; then
+              echo "::error file=coding-style.sh,title=Coding style error::Coding style error"
+              cat coding-style.log
+              exit 1
+          fi
 
   check_program_compilation_windows:
     name: Checks if the program compiles correctly on windows and executables files got created
